jdk.version=26.0.2+10
jdk.vendor=Eclipse Adoptium
jdk.name=Temurin
jdk.variant=temurin-26
jdk.trademark.line="'Adoptium' and 'Adoptium Eclipse Temurin' are trademarks of the Eclipse Adoptium Working Group."
jdk.releasenotes.link=https://adoptium.net/temurin/release-notes
jdk.maindownloadpage=https://adoptium.net/temurin/releases

jdk.linux.x64.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.2%2B10/OpenJDK26U-jdk_x64_linux_hotspot_26.0.2_10.tar.gz
jdk.linux.x64.sha=56f768372f6ca1e2eb4c5f46b78f627949e8dcfe9c9723926cf45a45faf35802

jdk.linux.arm.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.2%2B10/OpenJDK26U-jdk_aarch64_linux_hotspot_26.0.2_10.tar.gz
jdk.linux.arm.sha=f82aeb1d5b0ddb93d3bd81c20948bc560c0758993157202424c17e805e2effbb

jdk.windows.x64.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.2%2B10/OpenJDK26U-jdk_x64_windows_hotspot_26.0.2_10.zip
jdk.windows.x64.sha=0b532502e29a5d2babe608069f6df2423ae5e1aa714b715b560217cf8c6ce8ff

jdk.macos.arm.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.2%2B10/OpenJDK26U-jdk_aarch64_mac_hotspot_26.0.2_10.tar.gz
jdk.macos.arm.sha=4c9255ed5a9fa84ad6e25675bac6ba6a4906fc7878169d7369a1424157b50256

jdk.macos.x64.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.2%2B10/OpenJDK26U-jdk_x64_mac_hotspot_26.0.2_10.tar.gz
jdk.macos.x64.sha=def6874a01072031c2c850b03b4d29d4e97772af7cc2f564f6fae03f98eb6ea9