jdk.version=26.0.1+8
jdk.vendor=Eclipse Adoptium
jdk.name=Temurin
jdk.variant=temurin-26
jdk.trademark.line=i"'Adoptium' and 'Adoptium Eclipse Temurin' are trademarks Eclipse Adoptium (/əˈdɒptiəm/) Working Group."
jdk.releasenotes.link=https://adoptium.net/temurin/release-notes
jdk.maindownloadpage=https://adoptium.net/temurin/releases

jdk.linux.x64.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_x64_linux_hotspot_26.0.1_8.tar.gz
jdk.linux.x64.sha=8e512f13e575a43655fc92319436c94890c137b9035cc6bd6f9cf24239704d3a

jdk.linux.arm.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_aarch64_linux_hotspot_26.0.1_8.tar.gz
jdk.linux.arm.sha=613f9b2861dea937b24d5eca745ef8567733b377d0bb612195acaad0e3f61360

jdk.windows.x64.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_x64_windows_hotspot_26.0.1_8.zip
jdk.windows.x64.sha=81b35819085dd73a204c3219464c5f154cb111a526ec63dad793c0eefd469b3d

jdk.macos.arm.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_aarch64_mac_hotspot_26.0.1_8.tar.gz
jdk.macos.arm.sha=10c436258e24693ce8baf13dbffce98b77275797455e8b72510967547f13234a

jdk.macos.x64.url=https://github.com/adoptium/temurin26-binaries/releases/download/jdk-26.0.1%2B8/OpenJDK26U-jdk_x64_mac_hotspot_26.0.1_8.tar.gz
jdk.macos.x64.sha=032df492c8749864ee8b135e3d0ea5a17ef5c847309d5fdf8f1dd55e246b8319
