jdk.version=26+35
jdk.variant=zulu-26
jdk.vendor=Azul Zulu
jdk.name=Zulu
jdk.releasenotes.link=https://docs.azul.com/core/release-notes
jdk.trademark.line="'Azul' and 'Azul Zulu' are trademarks or registered trademarks of Azul Systems, Inc."
jdk.maindownloadpage=https://www.azul.com/downloads/

jdk.linux.x64.url=https://cdn.azul.com/zulu/bin/zulu26.28.59-ca-jdk26.0.0-linux_x64.tar.gz
jdk.linux.x64.sha=b637462b9c16bfb955f0240a4cdd5638f9523fb35de167bca189d38475f193fd

jdk.linux.arm.url=https://cdn.azul.com/zulu/bin/zulu26.28.59-ca-jdk26.0.0-linux_aarch64.tar.gz
jdk.linux.arm.sha=797fdab7a0d279fc1f59e7710fb031cf20bd0d4be366f1da151009fa9b5d3ca0

jdk.windows.x64.url=https://cdn.azul.com/zulu/bin/zulu26.28.59-ca-jdk26.0.0-linux_aarch64.tar.gz
jdk.windows.x64.sha=c112d51af20e00090aff3af2b11cb39e94362922c40c90623098064a5d1cd8ed

jdk.macos.arm.url=https://cdn.azul.com/zulu/bin/zulu26.28.59-ca-jdk26.0.0-macosx_aarch64.tar.gz
jdk.macos.arm.sha=f7d151adcc91b6a2513983066b0ca1db409df99d7a3a87ac31b21e60c978a5c7

jdk.macos.x64.url=https://cdn.azul.com/zulu/bin/zulu26.28.59-ca-jdk26.0.0-macosx_x64.tar.gz
jdk.macos.x64.sha=3a8d520c63eead9da76517291b5e58debc923b5ad7a48a654805a15a6f0807f9
