jdk.version=24.0.1
jdk.variant=zulu-24
jdk.vendor=Azul Zulu
jdk.name=Zulu
jdk.releasenotes.link=https://docs.azul.com/core/release-notes
jdk.trademark.line=Azul and Azul Zulu are trademarks or registered trademarks of Azul Systems, Inc.
jdk.maindownloadpage=https://www.azul.com/downloads/

jdk.linux.x64.url=https://cdn.azul.com/zulu/bin/zulu24.30.11-ca-jdk24.0.1-linux_x64.tar.gz
jdk.linux.x64.sha=12f6957c3a2a74d36d692cfee3aeeb949f15b5d80dad08bf0d3ed930d66d8659

jdk.linux.arm.url=https://cdn.azul.com/zulu/bin/zulu24.30.11-ca-jdk24.0.1-linux_aarch64.tar.gz
jdk.linux.arm.sha=e11e4ae574e0a51f64abd5961374a0bea553abc085bf26fde37cc0892b2ade4d

jdk.windows.x64.url=https://cdn.azul.com/zulu/bin/zulu24.30.11-ca-jdk24.0.1-win_x64.zip
jdk.windows.x64.sha=5bc4ee65329d533dea2d28b3773097f0f1b506f8e55c04c14fe64a8032929f7f

jdk.macos.arm.url=https://cdn.azul.com/zulu/bin/zulu24.30.11-ca-jdk24.0.1-macosx_aarch64.tar.gz
jdk.macos.arm.sha=a49b2ada029c4f2e38cdb15b4808fa29de55662d3de63286919a9df1c788cfb1

jdk.macos.x64.url=https://cdn.azul.com/zulu/bin/zulu24.30.11-ca-jdk24.0.1-macosx_x64.tar.gz
jdk.macos.x64.sha=56118e8996aca5779554b129d0c2595f18fffa8bc6826cbe8116f6059f4eba16
