name: Build

on:
  workflow_dispatch:
    inputs:
      netbeans-properties: 
        description: | 
          Provide the netbeans properties-name for this build.
          Defaults to the value netbeans.properties in 'build.properties'
          example: 'nb30-rc1'
        type: string
      jdk-properties: 
        description: | 
          Provide the jdk properties-name for this build. 
          Defaults to the value jdk.properties in 'build.properties'
          example: zulu-25
        type: string
      github-release: 
        description: |
          GitHub release tag to upload to, like 'nb29-zulu-25'.
          If not given, the aritfacts will not be uploaded to a release.
          NOTE: If given, the release must exist.
        type: string
        required: false
      sign-artifacts: 
        description: set to sign the windows and macos artifacts.
        type: boolean
        default: false
      build-deb-x64:
        description: 'Build Linux .deb for x86_64'
        type: boolean
      build-deb-arm:
        description: 'Build Linux .deb for aarch64'
        type: boolean
      build-rpm-x64:
        description: 'Build Linux .rpm for x86_64'
        type: boolean
      build-windows-x64:
        description: 'Build Windows .exe for x86_64'
        type: boolean
      build-macos-arm:
        description: 'Build macOS .pkg for aarch64'
        type: boolean
      build-macos-x64:
        description: 'Build macOS .pkg for x86_64'
        type: boolean

jobs:
  
  validate:
    name: Validate and cache
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Validate release tag
        if: ${{ inputs.github-release }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ inputs.github-release }}
        run: |
          if ! gh release view "${RELEASE_TAG}" &> /dev/null;
            then
              echo "Release ${RELEASE_TAG} does not exist"
              exit 1
          fi          
      - name: Validate netbeans.properties
        if: ${{ inputs.netbeans-properties }}
        env:
          NETBEANS_PROPERTIES: ${{ inputs.netbeans-properties }}
        run: |
          if [ ! -e  "${NETBEANS_PROPERTIES}.properties" ]; then
              echo "netbeans properties file ${NETBEANS_PROPERTIES}.properties does not exist"
              exit 1
          fi          
      - name: Validate jdk.properties
        if: ${{ inputs.jdk-properties }}
        env:
          JDK_PROPERTIES: ${{ inputs.jdk-properties }}
        run: |
          if [ ! -e  "${JDK_PROPERTIES}.properties" ]; then
              echo "netbeans properties file ${JDK_PROPERTIES}.properties does not exist"
              exit 1
          fi          
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties' ) }}
          enableCrossOsArchive: true
      - name: Validate and cache
        run: java Exec.java validate-cache
      - name: Upload Validated Properties
        if: ${{inputs.github-release}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
        run: |
          cat ${NETBEANS_PROPERTIES}.properties ${JDK_PROPERTIES}.properties > package.properties
          gh release upload ${{ inputs.github-release }} --clobber package.properties

  build-deb-x64:
    name: Build Linux .deb for x86_64
    if: ${{ inputs.build-deb-x64 }}
    needs: validate
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties') }}
          enableCrossOsArchive: true
      - name: Build
        env:
          DPKG_DEB_COMPRESSOR_TYPE: xz
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
        run: java Exec.java build linux x64 deb
      - name: Upload to release
        if: ${{ inputs.github-release }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./dist
        run: |
          gh release upload ${{ inputs.github-release }} --clobber *.deb
      - name: Upload to workflow
        if: ${{! inputs.github-release }}
        uses: actions/upload-artifact@v7
        with: 
          name: linux-deb-x64
          path: |
            dist/*.deb
            dist/*.deb.sha


  build-deb-arm:
    name: Build Linux .deb for arm64
    if: ${{ inputs.build-deb-arm }}
    needs: validate
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties') }}
          enableCrossOsArchive: true
      - name: Build
        env:
          DPKG_DEB_COMPRESSOR_TYPE: xz
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.netbeans-properties}}
        run: java Exec.java build linux arm deb
      - name: Upload
        if: ${{ inputs.github-release }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./dist
        run: |
          gh release upload ${{ inputs.github-release }} --clobber *.deb
      - name: Upload to workflow
        if: ${{! inputs.github-release }}
        uses: actions/upload-artifact@v7
        with: 
          name: linux-deb-arm64
          path: |
            dist/*.deb
            dist/*.deb.sha

  build-rpm-x64:
    name: Build Linux .rpm for x86_64
    if: ${{ inputs.build-rpm-x64 }}
    needs: validate
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties') }}
          enableCrossOsArchive: true
      - name: Install RPM tools
        run: |
          sudo apt update
          sudo apt install rpm
      - name: Build
        env:
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
        run: java Exec.java build linux x64 rpm
      - name: Upload
        if: ${{inputs.github-release}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./dist
        run: |
          gh release upload ${{ inputs.github-release }} --clobber *.rpm
      - name: Upload to workflow
        if: ${{! inputs.github-release }}
        uses: actions/upload-artifact@v7
        with: 
          name: linux-rpm-x64
          path: |
            dist/*.rpm
            dist/*.rpm.sha

  build-windows-x64:
    name: Build Windows .exe for x86_64
    if: ${{ inputs.build-windows-x64 }}
    needs: validate
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties') }}
          enableCrossOsArchive: true
      - name: Build
        env:
          INNOSETUP_PATH: 'C:\\Program Files (x86)\\Inno Setup 6\\iscc.exe'
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
        run: java Exec.java build windows x64 innosetup
      - name: Upload unsigned to workflow
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-exe-x64-unsigned
          path: |
            dist/*.exe
            dist/*.exe.sha
      - name: Sign with signpath
        if: ${{ inputs.sign-artifacts }}
        id: signing
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_SIGNER_TOKEN }}'
          organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID }}'
          project-slug: 'FoAN_installer'
          signing-policy-slug: 'globalsign'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          # we may have to wait a bit because the approver may be slow
          wait-for-completion-timeout-in-seconds: 86400
          wait-for-completion: true
          output-artifact-directory: signed
      - name: Upload to release
        if: ${{ inputs.github-release && inputs.sign-artifacts }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./signed
        run: |
          gh release upload ${{ inputs.github-release }} --clobber *.exe
      - name: Upload unsigned to release
        if: ${{ inputs.github-release && ! inputs.sign-artifacts }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./dist
        run: |
          gh release upload ${{ inputs.github-release }} --clobber *.exe

  build-macos-arm:
    name: Build macOS .pkg for arm64
    if: ${{ inputs.build-macos-arm }}
    needs: validate
    runs-on: macos-14
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties') }}
          enableCrossOsArchive: true
      - name: Install certificates
        if: ${{ vars.APP_CERT_ID }}
        env:
          APP_CERT_BASE64: ${{ secrets.APP_CERT_BASE64 }}
          INST_CERT_BASE64: ${{ secrets.INST_CERT_BASE64 }}
          APP_CERT_PASSWORD: ${{ secrets.APP_CERT_PASSWORD }}
          INST_CERT_PASSWORD: ${{ secrets.INST_CERT_PASSWORD }}
        run: |
          APP_CERT_PATH="$RUNNER_TEMP/app_cert.p12"
          INST_CERT_PATH="$RUNNER_TEMP/inst_cert.p12"
          KEYCHAIN_PATH="$RUNNER_TEMP/signing.keychain-db"
          KEYCHAIN_PASSWORD="$(openssl rand -base64 12)"
          ###
          echo -n "$APP_CERT_BASE64" | base64 --decode -o "$APP_CERT_PATH"
          echo -n "$INST_CERT_BASE64" | base64 --decode -o "$INST_CERT_PATH"
          ###
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security import "$APP_CERT_PATH" -P "$APP_CERT_PASSWORD" -t cert -f pkcs12 -k "$KEYCHAIN_PATH" -T /usr/bin/codesign
          security import "$INST_CERT_PATH" -P "$INST_CERT_PASSWORD" -t cert -f pkcs12 -k "$KEYCHAIN_PATH" -T /usr/bin/pkgbuild
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
      - name: Build
        env:
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
          APP_CERT_ID: ${{ vars.APP_CERT_ID }}
          INST_CERT_ID: ${{ vars.INST_CERT_ID }}
        run: java Exec.java build macos arm pkg
      - name: Upload to workflow
        uses: actions/upload-artifact@v7
        with:
          name: macos-pkg-arm64-unnotarized
          path: |
            dist/*.pkg
      - name: Notarize
          # upload and start notarization but do not wait for result
        env:
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ vars.APPLE_ID }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          echo "Create keychain profile"
          xcrun notarytool store-credentials "signer" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" \
             --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"
          mypackage=$(find dist -name "*.pkg" -maxdepth 1 -type f)
          echo "Notarize app ${mypackage}"
          xcrun notarytool submit ${mypackage} --keychain-profile "signer" --no-wait

  build-macos-x64:
    name: Build macOS .pkg for x86_64
    if: ${{ inputs.build-macos-x64 }}
    needs: validate
    runs-on: macos-14
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup caches
        uses: actions/cache@v4
        with:
          path: cache
          key: ${{ hashFiles('Exec.java', '*.properties') }}
          enableCrossOsArchive: true
      - name: Install certificates
        if: ${{ vars.APP_CERT_ID }}
        env:
          APP_CERT_BASE64: ${{ secrets.APP_CERT_BASE64 }}
          INST_CERT_BASE64: ${{ secrets.INST_CERT_BASE64 }}
          APP_CERT_PASSWORD: ${{ secrets.APP_CERT_PASSWORD }}
          INST_CERT_PASSWORD: ${{ secrets.INST_CERT_PASSWORD }}
        run: |
          APP_CERT_PATH="$RUNNER_TEMP/app_cert.p12"
          INST_CERT_PATH="$RUNNER_TEMP/inst_cert.p12"
          KEYCHAIN_PATH="$RUNNER_TEMP/signing.keychain-db"
          KEYCHAIN_PASSWORD="$(openssl rand -base64 12)"
          ###
          echo -n "$APP_CERT_BASE64" | base64 --decode -o "$APP_CERT_PATH"
          echo -n "$INST_CERT_BASE64" | base64 --decode -o "$INST_CERT_PATH"
          ###
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security import "$APP_CERT_PATH" -P "$APP_CERT_PASSWORD" -t cert -f pkcs12 -k "$KEYCHAIN_PATH" -T /usr/bin/codesign
          security import "$INST_CERT_PATH" -P "$INST_CERT_PASSWORD" -t cert -f pkcs12 -k "$KEYCHAIN_PATH" -T /usr/bin/pkgbuild
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychains -d user -s "$KEYCHAIN_PATH"
      - name: Build
        env:
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
          APP_CERT_ID: ${{ vars.APP_CERT_ID }}
          INST_CERT_ID: ${{ vars.INST_CERT_ID }}
        run: java Exec.java build macos x64 pkg
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-pkg-x64-unnotarized
          path: |
            dist/*.pkg
      - name: Notarize
        env:
          PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ vars.APPLE_ID }}
          PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ vars.APPLE_TEAM_ID }}
          PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          echo "Create keychain profile"
          xcrun notarytool store-credentials "signer" --apple-id "$PROD_MACOS_NOTARIZATION_APPLE_ID" \
             --team-id "$PROD_MACOS_NOTARIZATION_TEAM_ID" --password "$PROD_MACOS_NOTARIZATION_PWD"
          mypackage=$(find dist/ -name "*.pkg" -maxdepth 1 -type f)
          echo "Notarize app ${mypackage}"
          xcrun notarytool submit ${mypackage} --keychain-profile "signer" --no-wait



