name: Show

on:
  workflow_dispatch:
    inputs:
      jdk-properties:
        description: the properties file-name for the jdk to bundle
        type: string
      netbeans-properties:
        description: the properties file-name for netbeans to bundle
        type: string

jobs:
  show:
    name: Show config
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'
      - name: show
        env: 
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
          NETBEANS_PROPERTIES: ${{inputs.netbeans-properties}}
        run: java Exec.java show linux x86_64 deb
