name: Show

on:
  workflow_dispatch:
    inputs:
      jdk-properties:
        description: the properties file-name for the jdk to bundle
        type: string

jobs:
  show:
    name: Show config
    runs-on: ubuntu-24.04
    steps:
      - name: step1
        env: 
          JDK_PROPERTIES: ${{inputs.jdk-properties}}
        run: java Exec.java show linux x86_64 deb
