name:  Sign for Windows x64

on: 
  workflow_call:

jobs:
  sign:
    name: sign with signpath
    runs-on: windows-2022
    steps:
  # required for the artifact to be available on the GitHub server
      - name: upload-unsigned-artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with: 
          path: windows-exe-x64.zip
      - id: optional_step_id
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID}}'
          project-slug: 'win_sign_x64'
          signing-policy-slug: 'test-signing'
          github-artifact-id: '${{ steps.upload-unsigned-artifact.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: windows-exe-x64-signed.zip
